apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: retich-load-test
  namespace: k6
spec:
  parallelism: 5
  paused: "false"

  script:
    configMap:
      name: retich-load-test
      file: load-test.js

  runner:
    image: grafana/k6:latest
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
    env:
      - name: EMAIL
        valueFrom:
          secretKeyRef:
            name: retich-load-test-env
            key: EMAIL
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: retich-load-test-env
            key: PASSWORD
      - name: AUDIENCE
        valueFrom:
          secretKeyRef:
            name: retich-load-test-env
            key: AUDIENCE
